### ISSUE TITLE
发现一个问题，微信语音接不起来，一直转圈。我移植了别人的路由配置就好了，建议大佬优化。

### ISSUE THREAD

**Issue by rdgjiose** [TinrLin/sing-box#10]

**Comment by TinrLin** [comment]
下个版本clash配置将移除

**Comment by rdgjiose** [comment]
> 下个版本clash配置将移除

我用的就是你的脚本生成的singbox 客户端的配置，微信接不起来语音，一直在转圈。

**Comment by TinrLin** [comment]
日志贴出来

**Comment by rdgjiose** [comment]
> 日志贴出来

我弄不出来日志，我不是太明白。但是我我可以把两个路由配置发上来，您可以对比一下。上边是你的配置，下边是我粘贴别人的配置。替换成别人的路由配置微信语音就可以接起来了。您肯定可以看的懂。对比一下。另外我试着在你生成的/usr/local/etc/sing-box/config.json添加ECH配置死活不成功，启动sing-box老失败。寄托于您的自动脚本。呵呵，在这里谢谢大佬了。
  "route": {
    "geoip": {
      "download_url": "https://github.com/soffchen/sing-geoip/releases/latest/download/geoip.db",
      "download_detour": "select"
    },
    "geosite": {
      "download_url": "https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db",
      "download_detour": "select"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  },
#########################以下是别人的route配置###################################
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "outbound": "dns-out",
        "protocol": "dns"
      },
      {
        "clash_mode": "direct",
        "outbound": "direct"
      },
      {
        "clash_mode": "global",
        "outbound": "select"
      },
      {
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "geolocation-!cn",
        "outbound": "select"
      },
      {
        "geosite": "cn",
        "outbound": "direct"
      }
    ],
    "geoip": {
            "download_detour": "select"
        },
    "geosite": {
            "download_detour": "select"
        }
  },

**Comment by TinrLin** [comment]
那你就用下面那个吧，配置没有多大区别
