### ISSUE TITLE
GeoIP and GeoSite

### ISSUE THREAD

**Issue by alidxdydz** [TinrLin/sing-box#14]
Hi,

Could you please ask for the location at the beginning of the installation and if it is Iran, block these [GeoIP-Lite](https://github.com/chocolate4u/Iran-sing-box-rules/releases/latest/download/geoip-lite.db), [GeoSite-Lite](https://github.com/chocolate4u/Iran-sing-box-rules/releases/latest/download/geosite-lite.db), [SecurityIP](https://github.com/chocolate4u/Iran-sing-box-rules/releases/latest/download/security-ip.db), and [SecuritySite](https://github.com/chocolate4u/Iran-sing-box-rules/releases/latest/download/security.db) databases [[provided by Chocolate4U for sing-box](https://github.com/chocolate4u/Iran-sing-box-rules)] in Server side and add them to bypass in Client side?
Or just simply ask for URLs for these databases in the installation process.

`GeoIP-Lite` contains `ir` and `private`.
`GeoSite-Lite` contains `ir` and `ads`.
`SecurityIP` contains `phishing` and `malware`.
`SecuritySite` contains `category-ads-all`, `malware`, `phishing`, and `cryptominers`.

Thank you.

**Comment by TinrLin** [comment]
Please provide a complete routing rule

**Comment by TinrLin** [comment]
Server and client
