### ISSUE TITLE
QR

### ISSUE THREAD

**Issue by NoRRt** [TinrLin/sing-box#16]
Can you scan the configuration output of each protocol through QR  
for examples
![image](https://github.com/TinrLin/sing-box/assets/4822035/6a7b934c-d08b-47c1-9bdd-a9b07402c650)

# Construct and DISPLAY QR the resulting URL
        result_url=" 
        ipv4 : hy2://$password@$public_ipv4:$user_port?insecure=1&sni=www.google.com#HY2
        ---------------------------------------------------------------
        ipv6 : hy2://$password@[$public_ipv6]:$user_port?insecure=1&sni=www.google.com#HY2"
        echo -e "Config URL: \e[91m$result_url\e[0m" >/etc/hysteria2/user-config.txt # Red color for URL

        result_url2=" 
        ipv4 : hy2://PASSWORD@$public_ipv4:$user_port?insecure=1&sni=www.google.com#HY2
        ---------------------------------------------------------------
        ipv6 : hy2://PASSWORD@[$public_ipv6]:$user_port?insecure=1&sni=www.google.com#HY2"
        echo -e "Config URL: \e[91m$result_url2\e[0m" >/etc/hysteria2/config.txt # Red color for URL

        cat /etc/hysteria2/user-config.txt

        ipv4qr=$(grep -oP 'ipv4 : \K\S+' /etc/hysteria2/user-config.txt)
        ipv6qr=$(grep -oP 'ipv6 : \K\S+' /etc/hysteria2/user-config.txt)

**Comment by NoRRt** [comment]
It can be used for other protocols

**Comment by TinrLin** [comment]
Will consider adding it when I have time, but not now
