### ISSUE TITLE
 Your iptables script automatically opens ports 0, 80/tcp, and 80/udp. What are these ports used for?

### ISSUE THREAD

**Issue by rdgjiose** [TinrLin/sing-box#17]
I only add VLESS  single node,  automatically opens bellow ports:
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     udp  --  anywhere             anywhere             udp dpt:https
ACCEPT     udp  --  anywhere             anywhere             udp dpt:0
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     udp  --  anywhere             anywhere             udp dpt:80

**Comment by TinrLin** [comment]
80是用來申請證書的，妳說的0不知道你怎麼搞得，vps端口通常為1-65535，你的0解釋不了，腳本防火牆規則沒有妳說的0端口的規則
