### ISSUE TITLE
安装WireGuard 节点就无法使用了.NaiveProxy没有自定义证书安装选项.

### ISSUE THREAD

**Issue by chxgzs** [TinrLin/sing-box#19]
安装WireGuard 节点就无法使用了.NaiveProxy没有自定义证书安装选项,很奇怪,除了NaiveProxy自己定义了证书可以连接成功,其它的协议,无论我怎么调试都无法成功.脑袋都大了.

**Comment by TinrLin** [comment]
naive没有自签证书选项，可以自定义呀

**Comment by chxgzs** [comment]
以前还有你的TG联系,现在都找到不你了问.... 你帮我看看到底哪里出问题了.就是不成功.

**Comment by TinrLin** [comment]
油管里有tg机器人的联系方式
