### ISSUE TITLE
使用體驗和發現的問題

### ISSUE THREAD

**Issue by daiupapa** [TinrLin/sing-box#7]
小白一枚，拱手作揖。
1、使用腳本安裝Tuic或者reality的時候，無法自動獲取本機IP。不知道是不是我自己哪裡設置出錯了。只能自己手動將服務器IP填進sing-box的js文件中
2、自動生成的手機配置文件，不光可以在iPhone和ipad的sing-box客戶端上使用，也可以在mac端客戶端使用，很是驚喜。
3、如果安裝juicity，只有配置信息，沒有文件。

**Comment by LeePee7** [comment]
昨晚刚学习到大佬的一键脚本，也是这样，某些小鸡搭建hy2或tuic时无法获得本机ip，cf的dns代理和warp都没开，求大佬指点

**Comment by TinrLin** [comment]
tg上把你的错误信息发给我

**Comment by daiupapa** [comment]
已經修復好了感謝🙏

**Comment by LeePee7** [comment]
谢谢大佬，问题已解决
