### ISSUE TITLE
已经建立了Hysteria2节点，监听端口默认的443，再次运行脚本建立Naiveproxy节点，默认端口仍然是443，会和前一个节点的端口冲突吗

### ISSUE THREAD

**Issue by Triones009** [TinrLin/sing-box#9]
大佬好：您的脚本是我目前再github上见到的功能最全的一个脚本，水平有限，想请教，已经建立了Hysteria2节点，监听端口默认的443，再次运行脚本建立Naiveproxy节点，默认端口仍然是443，会和前一个节点的443端口冲突吗，还是说再建立其它类型节点，必须改成其它端口，不能使用脚本推荐的默认443端口。
最近几天，clash for windows删库跑路的信息在网上沸沸扬扬，甚至冲上了微博热搜，这里也祝大佬身体健康，注意安全。
一点小小建议，希望大佬能写一个比较全面的电脑端配置指南，很多使用者都是向我一样的半瓶水。
先给出一个我的提醒建议，安装脚本必须在root下运行，初始登录不是root，要用sudo -i命令切换到root，我知道有很多使用甲骨文的vps用户，登录使用的是ubuntu，使用密钥登录，在这个用户下安装脚本，权限不够，会失败

**Comment by TinrLin** [comment]
你说的端口配置问题不存在，因为脚本配置端口的时候会检测配置文件里是否已经使用过该端口，如果已经使用过的话你端口验证那里还设置默认的话过不了验证，会要求你更换端口，客户端配置指南下周会写
